version: 2

sources:
  - name: clinic
    database: cutini_demo
    schema: synthea
    tables:
      - name: organizations
      - name: encounters
      - name: conditions
      - name: procedures
      - name: claims
      - name: patients